### ISSUE TITLE
Omeka 2.6.1 - plugin

### ISSUE THREAD

**Issue by AngeloVenera** [DBinaghi/plugin-EmailNotification#2]
Hi
i'am trying to install this plugin in omeka, but i have this messages:

Email Notification

Versione 1.0.1 per Daniele Binaghi

Sends notification when new Item or Collection is added.

Questo non è un plugin valido.

**Comment by DBinaghi** [comment]
Hello, @AngeloVenera.
There were some inconsistencies in the code, everything should be working now, please download the latest release and try installing it.
Thanks.
